workflows:
  android-debug:
    name: An Toan Mat - Android APK

    environment:
      groups:
        - android

    scripts:
      - name: Build Android APK
        script: |
          gradle assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
