name: antoanmat
description: App bao ve mat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  system_alert_window: ^0.7.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/cartoon.png
